2025-05-14 17:35:23,257 ERROR: Exception on /newBoxProv [POST] [in C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Gustavo\code\curio\backend\app\api\routes.py", line 321, in new_box_prov
    cursor.execute("SELECT * FROM versionedElement WHERE ve_id = ?", (old_workflow[2],))
TypeError: 'NoneType' object is not subscriptable
2025-05-14 17:37:40,461 ERROR: Exception on /newBoxProv [POST] [in C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Gustavo\code\curio\backend\app\api\routes.py", line 321, in new_box_prov
    cursor.execute("SELECT * FROM versionedElement WHERE ve_id = ?", (old_workflow[2],))
TypeError: 'NoneType' object is not subscriptable
2025-05-14 17:40:19,499 ERROR: Exception on /newBoxProv [POST] [in C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Gustavo\code\curio\backend\app\api\routes.py", line 321, in new_box_prov
    cursor.execute("SELECT * FROM versionedElement WHERE ve_id = ?", (old_workflow[2],))
TypeError: 'NoneType' object is not subscriptable
2025-05-14 17:45:22,080 ERROR: Exception on /newBoxProv [POST] [in C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Gustavo\code\curio\backend\app\api\routes.py", line 321, in new_box_prov
    cursor.execute("SELECT * FROM versionedElement WHERE ve_id = ?", (old_workflow[2],))
TypeError: 'NoneType' object is not subscriptable
2025-05-14 17:54:55,943 ERROR: Exception on /newBoxProv [POST] [in C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gustavo\miniforge3\envs\backend-curio\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Gustavo\code\curio\backend\app\api\routes.py", line 321, in new_box_prov
    cursor.execute("SELECT * FROM versionedElement WHERE ve_id = ?", (old_workflow[2],))
TypeError: 'NoneType' object is not subscriptable
